# Generated by Django 6.0.7 on 2026-07-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_id_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_id_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='date_font_size',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='event',
            name='date_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='date_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_font_size',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='event',
            name='event_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='name_font_size',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='event',
            name='name_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='name_y',
            field=models.IntegerField(default=0),
        ),
    ]
