# Generated by Django 6.0.7 on 2026-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_certificate_id_x_event_certificate_id_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='certificate_id_x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='certificate_id_y',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_font_size',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_y',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_font_size',
            field=models.IntegerField(blank=True, default=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_y',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_font_size',
            field=models.IntegerField(blank=True, default=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_y',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
