# Generated by Django 6.0.7 on 2026-07-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='generated_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
